use_frameworks!

platform :ios, '13.0'

target 'TagsCollection_Example' do
  pod 'TagsCollection', :path => '../'

  target 'TagsCollection_Tests' do
    inherit! :search_paths
# dependency
    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 9.4.0'
  end
end
